### PR TITLE
Use Docusaurus

### PR DESCRIPTION
**Pull request by mdoryammilwalrus**

### CODE REVIEW

**Review by MotorTruck1221 — COMMENTED** [review]
I don't get why we need to change the code base... Nextra is fine

**Comment by mdoryammilwalrus** [comment]
The template looks kinda bad..

It _could_ be worse https://www.docz.site/

**Comment by MotorTruck1221** [comment]
> The template looks kinda bad..
> 
> It _could_ be worse https://www.docz.site/

I am open to changes.

Make sure the PR is updated with the current state and then i'll approve them

Also, docz.site is just *eww*

**Comment by MotorTruck1221** [comment]
> > The template looks kinda bad..
> > It _could_ be worse https://www.docz.site/
> 
> I am open to changes.
> 
> Make sure the PR is updated with the current state and then i'll approve them
> 
> Also, docz.site is just _eww_

@mdoryammilwalrus

**Comment by MotorTruck1221** [comment]
Also, for the love of PETE please use pnpm

**Review by MotorTruck1221 — CHANGES_REQUESTED** [review]
Update to current state of repo, don't change language (i'll do that later)

Use PNPM yarn is too slow

**Comment by MotorTruck1221** [comment]
If needed use yarn

**Comment by mdoryammilwalrus** [comment]
Better idea: New repo

**Comment by MotorTruck1221** [comment]
> Better idea: New repo

VALID

**Pull request closed without merging**
